### PR TITLE
http: outbound always send metric on service call

### LINKED ISSUE #397: http outbound does not send metric/ack when http request fails immediately

### PR DESCRIPTION
**Pull request by AlbsAgren**
This commit ensures that the outbound always sends metrics to the service manager even when a call fails immediately due to violated preconditions.

Resolves #397

### CODE REVIEW

File: middleware/http/include/http/outbound/state.h [hunk 1]
```diff
@@ -221,6 +225,15 @@ namespace casual
...
 
+         inline void maybe_metric()
+         {
+            if( pending.requests.empty() || metric)
+            {
+               common::communication::device::blocking::send( common::communication::instance::outbound::service::manager::device(), metric.message());
+               metric.clear();
+            }
+         }
+
```
Comment (lazan) [inline middleware/http/include/http/outbound/state.h]: `State` should never "do anything", other than mutate it's own state. 
This to reduce complexity. Other stuff actually do stuff and mutate state to reflect what's done.
Also, with this "rule" we don't need ask our self, where "to do this stuff" -> less confusion and more coherent code.
Move this to _handle_.

There might be stuff that is "done" in a few places in other `State` -> if so, it should be removed.

**Review by lazan — CHANGES_REQUESTED** [review]

File: middleware/http/include/http/outbound/state.h [hunk 2]
```diff
@@ -17,6 +17,8 @@
 #include "common/message/service.h"
 #include "common/domain.h"
 #include "common/predicate.h"
+#include "common/communication/ipc.h"
+#include "common/communication/instance.h"
```
Comment (lazan) [inline middleware/http/include/http/outbound/state.h]: Remove

**Review by lazan — APPROVED** [review]
Looking good.

**Review by ahhud — APPROVED** [review]
