### PR TITLE
domain: improve error messages

### LINKED ISSUE #315: Improve error messages when casual is unable to create domain lock file
When the casual domain is started and casual is unable to create or write to the domain lock file, the error messages doesn't really explain the error. Sometimes they're even misleading, such as "failed to remove file", when the actual problem was encountered during creation.

### PR DESCRIPTION
**Pull request by partickl**
Add more descriptive error messages and raise error if domain lock file cannot be created

Resolves #315

### CODE REVIEW

File: middleware/common/source/file.cpp [hunk 1]
```diff
@@ -133,7 +133,11 @@ namespace casual
 
          void rename( const std::filesystem::path& source, const std::filesystem::path& target)
          {
-            std::filesystem::rename( source, target);
+            std::error_code ec;
+            std::filesystem::rename( source, target, ec);
+            if (ec)
+               code::raise::error( code::casual::invalid_path, "failed to rename file, source: ", source, " -> target: ", target, ", error message: ", ec.message());
+
```
Comment (lazan) [inline middleware/common/source/file.cpp:140]: Nice.

File: middleware/common/source/domain.cpp [hunk 2]
```diff
@@ -129,10 +130,20 @@ namespace casual
...
-               std::ofstream output( temp_file);   
+               std::ofstream output( temp_file);
                auto archive = serialize::json::writer();
                archive << model;
                archive.consume( output);
+
+               if ( ! output)
+               {
+                  auto ec =  std::make_error_code( code::system::last::error());
+
```
Comment (lazan) [inline middleware/common/source/domain.cpp]: I don't think it's conformant to assume _failed std::ofstream_ sets posix errc. Or is it?
If not, just skip the "error message" in the raised error.

File: middleware/common/source/domain.cpp [hunk 3]
```diff
@@ -129,10 +130,20 @@ namespace casual
...
+                  if ( std::error_code temp_ec; ! std::filesystem::exists( temp_file, temp_ec))
+                     temp_file.release();
```
Comment (lazan) [inline middleware/common/source/domain.cpp]: I don't understand this. If the file does not exist, we release the _temp_file_. Why? Do we get an error in `scoped::Path` dtor otherwise?

Comment (partickl) [reply middleware/common/source/domain.cpp]: yes. if the path is non-empty it will try to remove the (non-existing) file. I'll move this check to the destructor for `scoped::Path`  instead

File: middleware/common/source/domain.cpp (hunk 2 above)
Comment (partickl) [reply middleware/common/source/domain.cpp]: seems to only be guaranteed when actually running on a posix compliant system.

**Review by lazan — APPROVED** [review]
Nice.
