### PR TITLE
service: fix routes dissapearing on config update

### LINKED ISSUE #431: Enabling a server does not add it as an instance in routes pointing to its services
Reproduce:

Boot the following domain:
```yaml
domain:
  name: test

  groups:
    - name: my-group
      enabled: false

  servers:
    - path: ${CASUAL_HOME}/example/bin/casual-example-server
      instances: 1
      memberships:
        - my-group

  services:
    -  name: casual/example/domain/name
       routes: [ my-route]
```

Try to call the route:
```
$ echo "" | casual buffer --compose | casual call --service my-route | casual buffer --extract
[xatmi:TPENOENT] TPENOENT
```

Enable the group:
```
$ casual configuration --enable-groups my-group
```

Call the route again:
```
$ echo "" | casual buffer --compose | casual call --service my-route | casual buffer --extract
[xatmi:TPENOENT] TPENOENT
```
Here one would expect the call to succeed since there is now an instance of the service to which the route points.

### PR DESCRIPTION
**Pull request by AlbsAgren**
This commit fixes an issue where services that did not have their configuration changed would lose their routes when the service manager received a runtime configuration update.

Resolves #431

### CODE REVIEW

File: middleware/service/unittest/source/manager/test_manager.cpp [hunk 1]
```diff
@@ -1226,5 +1226,43 @@ namespace casual
          }
       }
 
+      TEST( service_manager, runtime_update_routes)
```
Comment (AlbsAgren) [inline middleware/service/unittest/source/manager/test_manager.cpp:1219]: This is maybe a bit too specific...

Comment (lazan) [reply middleware/service/unittest/source/manager/test_manager.cpp:1219]: In what regard?

File: middleware/service/unittest/source/manager/test_manager.cpp [hunk 2]
```diff
@@ -1226,5 +1226,43 @@ namespace casual
...
+
+         auto domain = local::domain( R"(
+domain:
+   services:
+      -  name: a
+         routes: [ b]
+)");
+
+         {
+            auto state = local::call::state();
```
Comment (lazan) [inline middleware/service/unittest/source/manager/test_manager.cpp]: Hmm, SM should have a `state()` function in `unittest/utillity.h` that we should use?

File: middleware/service/unittest/source/manager/test_manager.cpp [hunk 3]
```diff
@@ -1226,5 +1226,43 @@ namespace casual
...
+         auto wanted = local::configuration::load( local::configuration::base, R"(
+domain:
+   services:
+      -  name: a
+         routes: [ b]
+      -  name: c
+         routes: [ d]
+)");
+
+         casual::configuration::model::transform( casual::domain::unittest::configuration::post( casual::configuration::model::transform( wanted)));
```
Comment (lazan) [inline middleware/service/unittest/source/manager/test_manager.cpp]: Why do you transform the result of `post` and not bother with the return?

File: middleware/service/unittest/source/manager/test_manager.cpp (hunk 2 above)
Comment (lazan) [reply middleware/service/unittest/source/manager/test_manager.cpp]: Hence, remove the `local::call::state()` function -> alter the stuff in this file that uses it.

File: middleware/service/unittest/source/manager/test_manager.cpp (hunk 1 above)
Comment (AlbsAgren) [reply middleware/service/unittest/source/manager/test_manager.cpp:1219]: I wondered if maybe it should test that the whole state has been correctly updated, rather than just the routes, but I'm not sure.

Comment (lazan) [reply middleware/service/unittest/source/manager/test_manager.cpp:1219]: > I wondered if maybe it should test that the whole state has been correctly updated, rather than just the routes, but I'm not sure.

I think it's better to be finer then coarser.

**Review by lazan — APPROVED** [review]
