### PR TITLE
ipc: fix discard while message is only partially received

### LINKED ISSUE #311: Error if tpcancel is called while in the midst of recieving a large reply
If tpcancel is called while the caller has recieved parts of the reply, only the already received parts will be discarded, leading to the following error when the subsequent parts are received.

`[casual:internal-out-of-bounds] added transport has too large offset: 162880 - current offset: 0: internal-out-of-bounds`

### PR DESCRIPTION
**Pull request by AlbsAgren**
Before: We cleared the partially complete message from the device cache when being told to discard. This caused an out-of-bounds error when subsequent parts of the message arrived.
Now: We wait til the entire message has a arrived before clearing it from the cache.

Resolves #311

The unittest could perhaps be done in a more simple way, open to suggestions.

### CODE REVIEW

File: middleware/common/include/common/communication/device.h [hunk 1]
```diff
@@ -259,11 +259,8 @@ namespace casual
 
             auto complete = algorithm::find_if( m_cache, [&]( auto& complete){ return complete.correlation() == correlation;});
 
-            if( complete)
+            if( complete && complete->complete())
```
Comment (lazan) [inline middleware/common/include/common/communication/device.h:262]: Ahh, nice! A lot better then what I thought we had to do! God work man!

File: middleware/common/unittest/source/communication/test_ipc.cpp [hunk 2]
```diff
@@ -598,5 +597,45 @@ namespace casual
...
+            transport.message.header.offset = std::distance( std::begin( complete.payload), part_begin);
+
+            native::blocking::send( destination.socket(), destination.address(), transport);
+
+            return part_end;
+         };
+
+         // The sender sends the first half of the complete message
+         auto part_begin = send_single_transport( complete, std::begin( complete.payload));
+
```
Comment (lazan) [inline middleware/common/unittest/source/communication/test_ipc.cpp:629]: Do a `device.flush()` just in case we run on a system that only have "space" for one transport at a time.

File: middleware/common/unittest/source/communication/test_ipc.cpp [hunk 3]
```diff
@@ -598,5 +597,45 @@ namespace casual
...
+         // The receiver discards the message by correlation
+         device.discard( correlation);
+
+         // Send the second half
+         send_single_transport( complete, part_begin);
+
+         // There should be no message for us to receive since the receiver has discarded it
+         unittest::Message receive_message;
+         EXPECT_NO_THROW({ EXPECT_FALSE( device::non::blocking::receive( device, receive_message, correlation)); });
```
Comment (lazan) [inline middleware/common/unittest/source/communication/test_ipc.cpp]: It feels kinda cramped with two gtest "predicate" in one line.  `EXPECT_NO_THROW` as a "scope"?

File: middleware/common/unittest/source/communication/test_ipc.cpp [hunk 4]
```diff
@@ -598,5 +597,45 @@ namespace casual
...
+
+            return part_end;
+         };
+
+         // The sender sends the first half of the complete message
+         auto part_begin = send_single_transport( complete, std::begin( complete.payload));
+
+         // The receiver discards the message by correlation
+         device.discard( correlation);
+
```
Comment (lazan) [inline middleware/common/unittest/source/communication/test_ipc.cpp:632]: Or `device.flush()`. here. At least before we send another one.

**Review by lazan — COMMENTED** [review]
An easy but brilliant fix. I have a few pointer on the the test-case though.

File: middleware/common/unittest/source/communication/test_ipc.cpp (hunk 3 above)
Comment (AlbsAgren) [reply middleware/common/unittest/source/communication/test_ipc.cpp]: Yeah, I wasn't sure about the NO_THROW, but it felt weird not having it since thats what failed pre-fix. But having it as a scope might be tidier.

**Review by lazan — APPROVED** [review]
Very good work.
