### PR TITLE
cli: fix gateway --list-connections to indicate inbound discovery forward

### LINKED ISSUE #147: casual gateway - cli listing of "connections" should show if inbound has discovery forward

### PR DESCRIPTION
**Pull request by lazan**
This patch prints `in*` as bound for inbound with configuration discovery forward = true

resolves #147

### CODE REVIEW

File: middleware/administration/unittest/source/cli/test_gateway.cpp [hunk 1]
```diff
@@ -0,0 +1,104 @@
+//!
+//! Copyright (c) 2022, The casual project
```
Comment (ahhud) [inline middleware/administration/unittest/source/cli/test_gateway.cpp:2]: 2022 -> 2023

**Review by ahhud — APPROVED** [review]

File: middleware/gateway/source/manager/admin/cli.cpp [hunk 2]
```diff
@@ -120,6 +120,7 @@ namespace casual
                      {
                         using Enum = decltype( value.bound);
                         case Enum::in: return "in";
+                        case Enum::in_forward: return "in*";
```
Comment (AlbsAgren) [inline middleware/gateway/source/manager/admin/cli.cpp:123]: How is the meaning of "in*" communicated to the user?

Comment (lazan) [reply middleware/gateway/source/manager/admin/cli.cpp:123]: I was looking for a `--legend` to add this info... There seems to be very little documentation about --list-connections, and I thought that was a separate issue.
