### PR TITLE
service: handle multiple busy lookups

### LINKED ISSUE #217: service - call inexplicably fails when starting domain under heavy load
The callee shows no trace of ever having received the call.

Working theory: the service manager sends too multiple 'busy' replies for the same lookup request.

### PR DESCRIPTION
**Pull request by AlbsAgren**
Before: we relied on the service manager only sending a single busy lookup reply before sending idle. The SM didnt always uphold this contract which would occasionally cause service calls to fail.

Now: we wait until we receive an idle reply irrespective of how many busy ones are sent beforehand.

Resolves #217

### CODE REVIEW

File: middleware/common/source/service/lookup.cpp [hunk 1]
```diff
@@ -69,7 +69,6 @@ namespace casual
             swap( lhs.m_correlation, rhs.m_correlation);
          }
 
-
          void Lookup::update( Reply&& reply)
```
Comment (AlbsAgren) [inline middleware/common/source/service/lookup.cpp:73]: I decided against removing this. Resetting m_correlation is used to indicate that we dont need to discard the pending lookup so it felt a bit tricky breaking this out into a free function.

File: middleware/common/source/service/lookup.cpp [hunk 2]
```diff
@@ -122,11 +121,18 @@ namespace casual
       {
          Trace trace{ "common::service::Lookup::operator()"};
```
Comment (AlbsAgren) [inline middleware/common/source/service/lookup.cpp:113]: The non-blocking ditto of this already appears to wait until it gets a 'non-busy' reply, so it should work as-is.

File: middleware/service/unittest/source/manager/test_manager.cpp [hunk 3]
```diff
@@ -1092,5 +1092,55 @@ namespace casual
...
+         // lookup 'local-service' again
+         common::service::Lookup lookup{ "local-service"};
+
+         // meanwhile, some process dies
+         {
+            common::message::event::process::Exit event;
+            event.state.pid = common::strong::process::id{ 42};
+            event.state.reason = decltype( event.state.reason)::exited;
+            common::communication::device::blocking::send( common::communication::instance::outbound::service::manager::device(), event);
+         }
```
Comment (lazan) [inline middleware/service/unittest/source/manager/test_manager.cpp:1119]: Nice

File: middleware/common/source/service/lookup.cpp [hunk 4]
```diff
@@ -122,11 +121,18 @@ namespace casual
...
          {
-            Reply result;
-            communication::device::blocking::receive( communication::ipc::inbound::device(), result, m_correlation);
-            update( std::move( result));
+            // wait until service is idle
+            // the second lookup::Reply should always be idle, but the service manager
+            // is currently not completely reliable in that regard
+            // TODO: rework this after fixing service manager
+            while( m_reply->busy())
+               update( communication::ipc::receive< Reply>());
```
Comment (lazan) [inline middleware/common/source/service/lookup.cpp:126]: NIce

**Review by lazan — APPROVED** [review]

**Review by lazan — APPROVED** [review]
Feels a lot simpler.

**Review by ahhud — APPROVED** [review]
